server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: repositorio-tpi
  datasource:
    url: jdbc:mysql://localhost:3306/db_repositorio_tpi
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ddl-auto: false
    show-sql: true
    open-in-view: false

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

media:
  location: mediafiles
